# Bitacoras onomásticas SEMEFO 1968-1982
# Catálogo procedencia

In [1]:
import pandas as pd
from numpy import nan
from helper_pandas import simplify_string

In [2]:
data = pd.read_pickle('data_clean/SEMEFO_BO_all.pkl')
data = data['Diagnostico']
data = data.replace('S-D',nan).dropna().to_list()
data = [[i.strip() for i in d.split('+')] for d in data]
data = [item for sublist in data for item in sublist if len(item)>0]
data = [[i.strip() for i in d.split(' x ')] for d in data]
data = [item for sublist in data for item in sublist if len(item)>0]
data = pd.Series(data)
data = data.value_counts().reset_index()
data.columns = ['valor','freq']
data

                 valor  freq
0                   TM  7990
1                  TCE  6881
2                   BN  5082
3                  CVG  1445
4                   CH  1409
...                ...   ...
2698            CVG CO     1
2699         HsPAFPsAC     1
2700                Re     1
2701               TCH     1
2702  AQxElectrocución     1

[2703 rows x 2 columns]

In [3]:
cat = pd.read_csv('catalogos/catalogo_diagnostico_simplificado.csv')
cat = {k:v for k,v in zip(cat['Data'],cat['Equivalencia'])}
cat
data['lower'] = data['valor'].apply(simplify_string, remove_special=True)
data['equi'] = data['valor'].map(cat)
data['equi_low'] = data['lower'].map({simplify_string(k):v for k,v in cat.items()})
data

                 valor  freq             lower equi equi_low
0                   TM  7990                tm   TM       TM
1                  TCE  6881               tce  TCE      TCE
2                   BN  5082                bn   BN       BN
3                  CVG  1445               cvg  CVG      CVG
4                   CH  1409                ch   CH       CH
...                ...   ...               ...  ...      ...
2698            CVG CO     1            cvg co  NaN      NaN
2699         HsPAFPsAC     1         hspafpsac  NaN      NaN
2700                Re     1                re  NaN      NaN
2701               TCH     1               tch  NaN      NaN
2702  AQxElectrocución     1  aqxelectrocucion  NaN      NaN

[2703 rows x 5 columns]

In [4]:
def replace_substring(s, replace=dict()):
    if type(s)==str:
        for k,v in replace.items():
            if k in s: return v
    return nan

rep_herida = {'hipc':'HIPC','hpaf':'HPAF','hsipc':'HIPC','hspaf':'HPAF'}
data['herida'] = data['lower'].apply(replace_substring, replace=rep_herida)

rep_common = data['equi_low'].head(20).to_list()
rep_common = {simplify_string(k):cat[k] for k in rep_common}
data['comun'] = data['lower'].apply(replace_substring, replace=rep_common)
data

                 valor  freq             lower equi equi_low herida comun
0                   TM  7990                tm   TM       TM    NaN    TM
1                  TCE  6881               tce  TCE      TCE    NaN   TCE
2                   BN  5082                bn   BN       BN    NaN    BN
3                  CVG  1445               cvg  CVG      CVG    NaN   CVG
4                   CH  1409                ch   CH       CH    NaN    CH
...                ...   ...               ...  ...      ...    ...   ...
2698            CVG CO     1            cvg co  NaN      NaN    NaN   CVG
2699         HsPAFPsAC     1         hspafpsac  NaN      NaN   HPAF   NaN
2700                Re     1                re  NaN      NaN    NaN   NaN
2701               TCH     1               tch  NaN      NaN    NaN    CH
2702  AQxElectrocución     1  aqxelectrocucion  NaN      NaN    NaN   NaN

[2703 rows x 7 columns]

In [6]:
data.notna().sum()

valor       2703
freq        2703
lower       2703
equi         271
equi_low     457
herida       260
comun        583
dtype: int64

In [14]:
data.groupby('equi_low').sum().sort_values(by='freq', ascending=False).index.to_list()

/tmp/ipykernel_40271/2005931610.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby('equi_low').sum().sort_values(by='freq', ascending=False).index.to_list()

['TM',
 'TCE',
 'BN',
 'CH',
 'CVG',
 'QUEM',
 'TCT',
 'LOC',
 'DISPENSA',
 'AOVA',
 'HPAFPC',
 'PN',
 'AQXT',
 'HPAFPT',
 'AXA',
 'ANEN',
 'ASB',
 'EX PSM',
 'HC',
 'TTA',
 'TMI',
 'TA',
 'TT',
 'HPAFP',
 'TB',
 'N',
 'HPAF',
 'TCA',
 'HPAFPA',
 'septicemia',
 'TCERV',
 'TCC',
 'HIPCPT',
 'HSPAFP',
 'ELECTROCUCION',
 'TP',
 'TCTA',
 'AN',
 'ENT',
 'TCCM',
 'TAP',
 'TCAP',
 'AE',
 'EP',
 'PER',
 'TCF',
 'HIPC',
 'HPAFPTA',
 'ASF',
 'GANG',
 'B',
 'EC',
 'INDETERMINADO',
 'VE',
 'HIPCPA',
 'TCET',
 'TTP',
 'HSPA',
 'HSIPCPS',
 'PANCREATITIS',
 'HSPAFPSTA',
 'HSPAFPST',
 'TCM',
 'TMIS',
 'TTAP',
 'INTOX',
 'P',
 'CVY',
 'HIPCPTA',
 'HSIPCPST',
 'HSPAFPC',
 'TCCT',
 'TMS',
 'ABORTO',
 'CL',
 'T',
 'HSIPCPSTA',
 'AT',
 'HSIP',
 'SH',
 'E',
 'DESNUT',
 'FCPN',
 'TCEA',
 'MENINGITIS',
 'PTE',
 'ANOXIA',
 'HIP',
 'NO COPIAS XOCO',
 'GASTROENTERITIS',
 'TCTP',
 'LOC INF MIOCARDIO',
 'HIPCPC',
 'IP',
 'HPAFPV',
 'HSPAFPSA',
 'TCRM',
 'AQ',
 'CISTICERCOSIS',
 'IA',
 'INF',
 'TROMBOSIS',
 'TCTAP',
 'HIPCPV',
 'NECROSIS',
 'MP',
 'ANENCEFALIA',
 'MENING',
 'VILLA',
 'HE',
 'I',
 'INTOX CO2',
 'ABORTO + S',
 'AXBRONCOASPIRACION',
 'CG',
 'BRONCO',
 'INTOX MED',
 'ECEP',
 'ENTER',
 'GASTROENT',
 'TCCA',
 'PL',
 'TCEYT',
 'INF MIOCARDIO',
 'ILEGIBLE',
 'AQMI',
 'CUG',
 'PIELONEFRITIS',
 'HEM',
 'AOVAS',
 'ASE',
 'BNB',
 'ANEURISMA',
 'MT',
 'DISP',
 'CRG',
 'ULCERAS',
 'BNXTMI',
 'HPIPCPC',
 'EPSM',
 'HPFPC',
 'MENIN',
 'INT MED',
 'EM',
 'TCCMA',
 'ANXVE',
 'INS',
 'HPAFPTYV',
 'INFARTO PULMONAR',
 'TCFYCM',
 'ENCEFALOMALASIA',
 'ABSESO HEP',
 'EA',
 'TUMOR',
 'FD',
 'FLEGMON',
 'TTC',
 'HCAM',
 'AN POS',
 'AXBRONCO',
 'AQM',
 'SXCUADRO DE OBS SIGMOIDES',
 'TCABN',
 'T ENCEFALICO',
 'T VAG',
 'SALICILI',
 'ASHS',
 'TC DORSAL',
 'RUP UTERINA',
 'ECEPCVG',
 'AOMI',
 'AOA',
 'VIOLACION',
 'TUMURACION MALIGNA DE RINON',
 'TTP Y MS',
 'AC',
 'ACN',
 'TTAF',
 'AECA',
 'AN + ABORTO',
 'AN + AOVA',
 'TMSITS',
 'ANA',
 'AND',
 'ANG',
 'TCMYT',
 'RC',
 'TCFYCT',
 'TCF Y CM',
 'ANP PREVIA',
 'ANRU',
 'RETENCION PLACEN',
 'MALF CONGENITAS',
 'RB',
 'HEM POST',
 'BYTT',
 'HSPAFAC',
 'CARDIOPATIA',
 'CPN',
 'CREP',
 'HPAFP CARA Y C',
 'CUADRO SEPTICO POR ABORTO',
 'HISPST',
 'CVB',
 'CVG INTOX ARESEMICO',
 'DISCRACIA',
 'HEMPUL',
 'H INTRA CER',
 'AVA',
 'GLOMERULO',
 'DPSM',
 'FRAC',
 'FMI',
 'FCN',
 'FAM',
 'EPB COMP DE PARTO DISTOSICO',
 'EP INTOX CI',
 'EP E INS RENAL',
 'ENTCOLITIS',
 'ENTA',
 'EN ES',
 'BR Y E',
 'HSPAPPTYA',
 'IMOD',
 'BNXPER UTERINO',
 'QOVQ',
 'POST LEGRADO',
 'PN TCE',
 'AVC',
 'PG',
 'PERIT NO T',
 'AVEN',
 'PEM',
 'PEGM',
 'PD',
 'AXASPPOST PART',
 'NXBRONCOASP',
 'MPYB',
 'MORDEDURAS ROEDORES',
 'MENINGITIS T',
 'MANIOBRAS OBSTR',
 'LOCH',
 'LOCCHN',
 'LOC TROM CORONARIA',
 'LO TROMBOSIS',
 'INTOXTAP',
 'INTOX CIA',
 'BNXMANIOBRAS ABORTIVAS',
 'INSEP',
 'INFARTOS PS CEREBRO',
 'HPRFPC']