# Bitacoras onomásticas SEMEFO 1968-1982
# Catálogo procedencia

In [1]:
import pandas as pd
from numpy import nan
from helper_pandas import simplify_string

In [2]:
cat = pd.read_csv('data_raw/procedencia_temp.csv')
cat['Procedencia'] = cat['Procedencia'].apply(simplify_string, str_case=None)
cat['Equivalencia'] = cat['Equivalencia'].apply(simplify_string, str_case=None)
cat

,Procedencia,Freq,Equivalencia,Direccion,Alcaldia
0,10a,568,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
1,10,232,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
2,10a deleg,53,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
3,10A,29,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
4,10a Del.,24,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
...,...,...,...,...,...
423,X-1,143,X-1,Coordinación Territorial 1 Xochimilco (Col San...,Xochimilco
424,X-I,77,X-1,Coordinación Territorial 1 Xochimilco (Col San...,Xochimilco
425,Xochimilco,74,XO,Xochimilco,Xochimilco
426,XO,17,XO,Xochimilco,Xochimilco
427,Xochimilco,2,XO,Xochimilco,Xochimilco

In [3]:
cat.drop('Freq', axis=1).drop_duplicates()

,Procedencia,Equivalencia,Direccion,Alcaldia
0,10a,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
1,10,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
2,10a deleg,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
3,10A,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
4,10a Del.,10A,Ministerio Público 10 (Col Santa Cruz Atoyac),Benito Juárez
...,...,...,...,...
421,V. Obregon,VO,Villa Obregon,NaN
423,X-1,X-1,Coordinación Territorial 1 Xochimilco (Col San...,Xochimilco
424,X-I,X-1,Coordinación Territorial 1 Xochimilco (Col San...,Xochimilco
425,Xochimilco,XO,Xochimilco,Xochimilco
426,XO,XO,Xochimilco,Xochimilco