In [1]:
import pandas as pd
from numpy import nan
from helper_pandas import *

import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud


from joblib import load

in_file = "data_clean/HBO_clean.pkl"
with open(in_file, 'rb') as f:
     df = load(f)

#Quitar filas vacias
df = df[df['Conocido_desconocido']!='S-D']
df.tail()

,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Fecha_año,Fecha_mes,Fecha_semana,...,Diagnostico_clasificacion,Procedencia_transcrito,Procedencia_estandar,Procedencia_extendido,Procedencia_alcaldia,Numero_acta_transcrito,Expediente_SEMEFO_transcrito,Bitacora_ingresos,Foja_transcrito,Observaciones
ID,,,,,,,,,,,,,,,,,,,,,
BO_1982_07489,S-D,placenta,NaN,NaN,NaN,1982-06-05,1982-06-05,1982.0,6.0,22,...,NaN,15a,GAM-2,Coord Territorial 2 Gustavo A Madero (Col Arag...,Gustavo A Madero,960,3079,semefo_df_bo_1982,156,NaN
BO_1982_07490,S-D,5 dedos del pie derecho de desconocido,NaN,NaN,NaN,1982-06-05,1982-06-05,1982.0,6.0,22,...,NaN,32a,COY-2,Coord Territorial 2 Coyoacan (Col Romero de Te...,Coyoacan,950,3060,semefo_df_bo_1982,156,NaN
BO_1982_07491,S-D,dedo de desconocido,NaN,NaN,NaN,1982-11-19,1982-11-19,1982.0,11.0,46,...,NaN,32a,COY-2,Coord Territorial 2 Coyoacan (Col Romero de Te...,Coyoacan,2005,6389,semefo_df_bo_1982,156,NaN
BO_1982_07492,S-D,4 dedos de desconocido,NaN,NaN,NaN,1982-11-28,1982-11-28,1982.0,11.0,47,...,NaN,27a,XO-2,Coord Territorial 2 Xochimilco (Barrio de San ...,Xochimilco,959,6528,semefo_df_bo_1982,156,NaN
BO_1982_07493,S-D,osamenta de desconocido,NaN,NaN,NaN,1982-10-11,1982-10-11,1982.0,10.0,41,...,NaN,9a,MH-1,Coord Territorial 1 Miguel Hidalgo – Hospital ...,Miguel Hidalgo,4193,5629,semefo_df_bo_1982,156,no se recibio necropsia. es una osamenta.

In [2]:
from matplotlib.colors import LinearSegmentedColormap

dic_color = {'Poblacion':'#0504aa', 'S-D':'#999999', 'S-D (DF)':'#d9d9d9', 'Masculino':'#377eb8', 'Masculino (DF)':'#80b1d3', 
             'Femenino':'#984ea3', 'Femenino (DF)':'#bebada', 
             'Conocido':'#4daf4a', 'Desconocido':'#dbb40c', 
             'Cadáver conocido':'#04d8b2', 'Cadáver desconocido':'#fdff52', 
             'Recién nacido':'#c875c4', 
             'Feto':'#ff7f00', 
             'Miembros':'#f781bf', 
             'Restos óseos':'#c85a53', }

gray_to_green = LinearSegmentedColormap.from_list('gray_to_green', ['#d9d9d9', '#2a7e19'])

## Diagnostico
'Diagnostico_transcrito', 
'Diagnostico_estandar',
'Diagnostico_extendido', 
'Diagnostico_clasificacion',

In [22]:
diag = pd.read_csv('catalogos/cat_diag_sustitucion.csv')
diag = diag[diag['Freq']>=5]
diag['Separado'] = diag['Diagnostico_estandar'].apply(lambda s: s.split('+'))
diag

,Diagnostico_transcrito,Diagnostico_estandar,Diagnostico_extendido,Freq,Npartes,Nfalta,IDs,Diagnostico_clasificacion,Separado
0,S-D,S-D,sin datos,55878,1,0,"BO_1968_00001,BO_1968_00002,BO_1968_00003,BO_1...",NaN,[S-D]
1,TM,TM,traumatismo multiple,7505,1,0,"BO_1974_00019,BO_1974_00020,BO_1974_00026,BO_1...",Trauma,[TM]
2,TCE,TCE,traumatismo craneo encefalico,5939,1,0,"BO_1974_00018,BO_1974_00021,BO_1974_00030,BO_1...",Trauma,[TCE]
3,BN,BN,bronconeumonia,1826,1,0,"BO_1974_00005,BO_1974_00008,BO_1974_00011,BO_1...",Enfermedades del sistema respiratorio,[BN]
4,CVG,CVG,congestion visceral generalizada,1287,1,0,"BO_1974_00151,BO_1974_00165,BO_1974_00166,BO_1...",NaN,[CVG]
...,...,...,...,...,...,...,...,...,...
323,TCerT,TCerT,traumatismo cervico torax,5,1,0,"BO_1975_02209,BO_1976_04081,BO_1977_01539,BO_1...",Trauma,[TCerT]
324,TCT+,TCT,traumatismo craneo torax,5,1,0,"BO_1976_03525,BO_1976_03835,BO_1977_05486,BO_1...",Trauma,[TCT]
325,TMS,TMiS,traumatismo miembro superior,5,1,0,"BO_1974_05591,BO_1974_05597,BO_1979_00767,BO_1...",Trauma,[TMiS]
326,TM+P,TPMi,traumatismo pelvis miembro,5,1,0,"BO_1975_01210,BO_1976_01742,BO_1976_02246,BO_1...",Trauma,[TPMi]
327,TEC,Trau,traumatismo,5,1,0,"BO_1974_01276,BO_1977_01654,BO_1977_05826,BO_1...",Trauma,[Trau]

In [26]:
ignore = ['BN','PN','N', 'Septi']

for i in ignore:
    diag[i] = diag['Separado'].apply(lambda s:'BN' in s)

#diag.loc[diag['Npartes']>1,['Diagnostico_estandar','Diagnostico_clasificacion']].value_counts()
diag

,Diagnostico_transcrito,Diagnostico_estandar,Diagnostico_extendido,Freq,Npartes,Nfalta,IDs,Diagnostico_clasificacion,Separado,BN,PN,N,Septi
0,S-D,S-D,sin datos,55878,1,0,"BO_1968_00001,BO_1968_00002,BO_1968_00003,BO_1...",NaN,[S-D],False,False,False,False
1,TM,TM,traumatismo multiple,7505,1,0,"BO_1974_00019,BO_1974_00020,BO_1974_00026,BO_1...",Trauma,[TM],False,False,False,False
2,TCE,TCE,traumatismo craneo encefalico,5939,1,0,"BO_1974_00018,BO_1974_00021,BO_1974_00030,BO_1...",Trauma,[TCE],False,False,False,False
3,BN,BN,bronconeumonia,1826,1,0,"BO_1974_00005,BO_1974_00008,BO_1974_00011,BO_1...",Enfermedades del sistema respiratorio,[BN],True,True,True,True
4,CVG,CVG,congestion visceral generalizada,1287,1,0,"BO_1974_00151,BO_1974_00165,BO_1974_00166,BO_1...",NaN,[CVG],False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,TCerT,TCerT,traumatismo cervico torax,5,1,0,"BO_1975_02209,BO_1976_04081,BO_1977_01539,BO_1...",Trauma,[TCerT],False,False,False,False
324,TCT+,TCT,traumatismo craneo torax,5,1,0,"BO_1976_03525,BO_1976_03835,BO_1977_05486,BO_1...",Trauma,[TCT],False,False,False,False
325,TMS,TMiS,traumatismo miembro superior,5,1,0,"BO_1974_05591,BO_1974_05597,BO_1979_00767,BO_1...",Trauma,[TMiS],False,False,False,False
326,TM+P,TPMi,traumatismo pelvis miembro,5,1,0,"BO_1975_01210,BO_1976_01742,BO_1976_02246,BO_1...",Trauma,[TPMi],False,False,False,False
327,TEC,Trau,traumatismo,5,1,0,"BO_1974_01276,BO_1977_01654,BO_1977_05826,BO_1...",Trauma,[Trau],False,False,False,False

In [27]:
diag['BN']

0      False
1      False
2      False
3       True
4      False
       ...
323    False
324    False
325    False
326    False
327    False
Name: BN, Length: 328, dtype: bool

## Procedencia
'Procedencia_transcrito', 
'Procedencia_estandar',
'Procedencia_extendido', 
'Procedencia_alcaldia',
'Numero_acta_transcrito'

## Conocido_desconocido
'Conocido_desconocido',

tabla por grupo de edad y sexo de principales causas de muerte